### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by niel96** [mwhea/Manifold_Trading_Bots#1]
Dear,

is this software still up to date? 
I seem to be getting a few errors. So i just have to put a .env file in my root with username + api key + api url? And then it should work?

### Issue 2: TypeError: Cannot read properties of undefined (reading '0')

How does your env file exactly look like? Sorry i'm still a noob when it comes to things like this.

Regards

**Comment by niel96** [comment]
This is the full error. Any idea what it could be?

C:\Users\niel\Manifold_Trading_Bots>npm start

> manifold-bots@1.0.0 start
> node src/botOrchestrator.js

TypeError: Invalid URL
    at new URL (node:internal/url:796:36)
    at new Request (file:///C:/Users/niel/Manifold_Trading_Bots/node_modules/node-fetch/src/request.js:55:16)
    at file:///C:/Users/niel/Manifold_Trading_Bots/node_modules/node-fetch/src/index.js:51:19
    at new Promise (<anonymous>)
    at fetch (file:///C:/Users/niel/Manifold_Trading_Bots/node_modules/node-fetch/src/index.js:49:9)
    at latestBets (file:///C:/Users/niel/Manifold_Trading_Bots/src/api.js:11:24)
    at Whaler.additionalConstruction (file:///C:/Users/niel/Manifold_Trading_Bots/src/Whaler.js:97:35)
    at file:///C:/Users/niel/Manifold_Trading_Bots/src/botOrchestrator.js:29:14 {
  code: 'ERR_INVALID_URL',
  input: 'undefined/bets?limit=1'
}
[2024-04-4 5:18:02.400 AM] ERROR: Failed to update blacklist
file:///C:/Users/niel/Manifold_Trading_Bots/src/Whaler.js:97
        this.lastBetSeen = (await latestBets(1))[0].id;
                                                ^

TypeError: Cannot read properties of undefined (reading '0')
    at Whaler.additionalConstruction (file:///C:/Users/niel/Manifold_Trading_Bots/src/Whaler.js:97:49)
    at async file:///C:/Users/niel/Manifold_Trading_Bots/src/botOrchestrator.js:29:1

Node.js v20.12.1
